group: 共通設定・システム設定・契約設定
spec_file: tests/system-settings.spec.js
base_url: '{{ TEST_BASE_URL }}'
cases:
- case_no: 10-1
  sheet: A
  feature: 共通設定
  category: テーブル
  description: テーブルの順番入れ替えを行う。
  expected: エラーなくテーブルの順番変更が行えること。
- case_no: 10-2
  sheet: A
  feature: 共通設定
  category: テーブル
  description: テーブル情報詳細表示を行う。
  expected: エラーなくテーブル詳細情報の表示が行えること。
- case_no: 10-3
  sheet: A
  feature: 共通設定
  category: テーブル
  description: テーブル定義の変更を行う。
  expected: エラーなくテーブル定義の変更が行えること。
- case_no: 10-4
  sheet: A
  feature: 共通設定
  category: テーブル
  description: テーブルの削除を行う。
  expected: エラーなくテーブルの削除が行えること。
- case_no: 24-1
  sheet: A
  feature: その他設定
  category: 新規ユーザーログイン時のパスワードリセット
  description: '①「その他設定」より「新規ユーザーのログイン時のパスワードリセットをOFFにする」にチェックを入れて「更新」ボタンをクリック


    ②新規ユーザーを作成


    ③新規ユーザーでログイン'
  expected: 新規ユーザーで初回ログイン時、パスワード変更が画面が表示されないこと。
- case_no: 24-2
  sheet: A
  feature: その他設定
  category: 新規ユーザーログイン時のパスワードリセット
  description: '①「その他設定」より「新規ユーザーのログイン時のパスワードリセットをOFFにする」にチェックを入れずに「更新」ボタンをクリック


    ②新規ユーザーを作成


    ③新規ユーザーでログイン'
  expected: 新規ユーザーで初回ログイン時、パスワード変更が画面が表示されること。
- case_no: 58-1
  sheet: A
  feature: その他設定
  category: ログイン時に利用規約を表示する
  description: '①「その他設定」より、「初回ログイン時に利用規約を表示する」の有効にチェックを入れ「更新」ボタンをクリック。

    ②「マスターユーザー」でログインする。

    ③「通常ユーザー」でログインする。'
  expected: マスターユーザー／通常ユーザーともにログイン時に利用規約が表示されること。
- case_no: 58-2
  sheet: A
  feature: その他設定
  category: ログイン時に利用規約を表示しない
  description: '①「その他設定」より、「初回ログイン時に利用規約を表示する」の有効にチェックを外し「更新」ボタンをクリック。

    ②「マスターユーザー」でログインする。

    ③「通常ユーザー」でログインする。'
  expected: マスターユーザー／通常ユーザーともにログイン時に利用規約が表示されなくなること。
- case_no: 7-1
  sheet: A
  feature: システム利用状況
  category: '-'
  description: ユーザー数を増やす。
  expected: システム利用状況のユーザー数の表示が増えること。
- case_no: 7-2
  sheet: A
  feature: システム利用状況
  category: '-'
  description: ユーザー数を減らす。
  expected: システム利用状況のユーザー数の表示が減ること。
- case_no: 7-3
  sheet: A
  feature: システム利用状況
  category: '-'
  description: テーブル数を増やす。
  expected: システム利用状況のテーブル数の表示が増えること。
- case_no: 7-4
  sheet: A
  feature: システム利用状況
  category: '-'
  description: テーブル数を減らす。
  expected: システム利用状況のテーブル数の表示が減ること。
- case_no: 7-5
  sheet: A
  feature: システム利用状況
  category: '-'
  description: メール通知を実施する。
  expected: システム利用状況のメール通知数の表示が増えること。
- case_no: 8-1
  sheet: A
  feature: その他設定
  category: 二段階認証
  description: 二段階認証を有効化する。
  expected: 2段階認証の設定が行われること。
- case_no: 8-2
  sheet: A
  feature: その他設定
  category: 二段階認証
  description: 二段階認証を無効化する。
  expected: 2段階認証の設定が解除されること。
- case_no: 9-10
  sheet: A
  feature: 共通設定
  category: レコード
  description: レコードの詳細情報表示を行う。
  expected: エラーなくレコードの詳細情報表示が行えること。
- case_no: 9-11
  sheet: A
  feature: 共通設定
  category: レコード
  description: レコード編集を行う。
  expected: エラーなくレコードの編集が行えること。
- case_no: 9-12
  sheet: A
  feature: 共通設定
  category: レコード
  description: レコード削除を行う。
  expected: エラーなくレコードの削除が行えること。
- case_no: 9-1
  sheet: A
  feature: 共通設定
  category: レコード
  description: 追加を選択しレコードの追加を行う。
  expected: エラーなくレコード追加が可能なこと。
- case_no: 9-4
  sheet: A
  feature: 共通設定
  category: レコード
  description: 全てのデータ削除を選択する。
  expected: エラーなく該当テーブルのレコード情報が全て削除されること。
- case_no: 9-5
  sheet: A
  feature: 共通設定
  category: レコード
  description: 集計を選択しデータ集計を行う。
  expected: エラーなく設定した情報が集計し表示されること。
- case_no: 9-6
  sheet: A
  feature: 共通設定
  category: レコード
  description: チャート追加を行う。
  expected: エラーなく設定した内容でチャート追加が行われること。
- case_no: 9-8
  sheet: A
  feature: 共通設定
  category: レコード
  description: データ検索を行う。
  expected: エラーなく検索結果に基づいた内容でレコード検索が行えること。
- case_no: 9-9
  sheet: A
  feature: 共通設定
  category: レコード
  description: データ編集を行う。
  expected: エラーなくレコード編集が行えること。
- case_no: 10-1
  sheet: B
  feature: 共通設定
  category: テーブル
  description: テーブルの順番入れ替えを行う。
  expected: エラーなくテーブルの順番変更が行えること。
- case_no: 10-2
  sheet: B
  feature: 共通設定
  category: テーブル
  description: テーブル情報詳細表示を行う。
  expected: エラーなくテーブル詳細情報の表示が行えること。
- case_no: 10-3
  sheet: B
  feature: 共通設定
  category: テーブル
  description: テーブル定義の変更を行う。
  expected: エラーなくテーブル定義の変更が行えること。
- case_no: 10-4
  sheet: B
  feature: 共通設定
  category: テーブル
  description: テーブルの削除を行う。
  expected: エラーなくテーブルの削除が行えること。
- case_no: 130-01
  sheet: B
  feature: 契約設定
  category: 'Paypal支払い

    ※機能変更に伴い本テスト不要'
  description: '①「https://demo-cw.pigeon-demo.com/api/admin/debug-reset-payment」を実行し「RESET
    PAYMENT DONE」が表示されることを確認する。

    →契約設定がリセットされる事を確認する。

    ② メニューより、「契約設定」→「Paypalサブスクリプション登録」を選択する。

    ③PaypalではID/パスワードはテスト用の以下にて手続きを進める。

    　ID：ishikawa-buyer@loftal.jp ／password:testtest'
  expected: 契約が問題なく完了すること。
- case_no: 131-02
  sheet: B
  feature: 契約設定
  category: 'カード支払い

    ※機能変更に伴い本テスト不要'
  description: '①「https://demo-cw.pigeon-demo.com/api/admin/debug-reset-payment」を実行し「RESET
    PAYMENT DONE」が表示されることを確認する。

    →契約設定がリセットされる事を確認する。

    ② メニューより、「契約設定」→「デビットカードまたはクレジットカード」を選択する。

    ③「国地域」→「日本」、「カード」を選択する。

    ④カード番号にはVISAを選択し、カード番号は以下サイトより取得したテスト用のカード番号を利用する。

    　https://www.getcreditcardnumbers.com/

    ⑤その他、情報についてはテスト用に自由に登録し、「PayPalアカウントを作成しますか? (すぐに完了します。)」は「いいえ」を選択し、「同意して定期購入」をクリックする。

    　※(注)カードの有効期限については未来日付にすること。'
  expected: 契約が問題なく完了すること。
- case_no: 24-1
  sheet: B
  feature: その他設定
  category: 新規ユーザーログイン時のパスワードリセット
  description: '①「その他設定」より「新規ユーザーのログイン時のパスワードリセットをOFFにする」にチェックを入れて「更新」ボタンをクリック


    ②新規ユーザーを作成


    ③新規ユーザーでログイン'
  expected: 新規ユーザーで初回ログイン時、パスワード変更が画面が表示されないこと。
- case_no: 24-2
  sheet: B
  feature: その他設定
  category: 新規ユーザーログイン時のパスワードリセット
  description: '①「その他設定」より「新規ユーザーのログイン時のパスワードリセットをOFFにする」にチェックを入れずに「更新」ボタンをクリック


    ②新規ユーザーを作成


    ③新規ユーザーでログイン'
  expected: 新規ユーザーで初回ログイン時、パスワード変更が画面が表示されること。
- case_no: 284-1
  sheet: B
  feature: 契約設定
  category: クレジットカード払い(Stripe)
  description: "①「https://demo-cw.pigeon-demo.com/api/admin/debug-reset-payment」を実行し「RESET\
    \ PAYMENT DONE」が表示されることを確認する。 \n→契約設定がリセットされる事を確認する。 \n② メニューより、「契約設定」→「クレジットカード支払い」を選択する。\n\
    ③以下URLよりテスト用のクレカ番号を確認し、契約内容入力後手続きを進める。\nhttps://stripe.com/docs/testing#cards\n\
    ④契約が完了したを確認する。\n⑤メニューより、「契約設定」を選択する。\n\nhttps://henmi022.pigeon-demo.com/api/admin/debug-reset-payment"
  expected: 現在のプランの表示が契約通りの内容となること。
- case_no: 58-1
  sheet: B
  feature: その他設定
  category: ログイン時に利用規約を表示する
  description: '①「その他設定」より、「最初に利用規約を表示する」の有効にチェックを入れ「更新」ボタンをクリック。

    ②「マスターユーザー」でログインする。

    ③「通常ユーザー」でログインする。'
  expected: マスターユーザー／通常ユーザーともにログイン時に利用規約が表示されること。
- case_no: 58-2
  sheet: B
  feature: その他設定
  category: ログイン時に利用規約を表示しない
  description: '①「その他設定」より、「最初に利用規約を表示する」の有効にチェックを外し「更新」ボタンをクリック。

    ②「マスターユーザー」でログインする。

    ③「通常ユーザー」でログインする。'
  expected: マスターユーザー／通常ユーザーともにログイン時に利用規約が表示されなくなること。
- case_no: 7-1
  sheet: B
  feature: システム利用状況
  category: '-'
  description: ユーザー数を増やす。
  expected: システム利用状況のユーザー数の表示が増えること。
- case_no: 7-2
  sheet: B
  feature: システム利用状況
  category: '-'
  description: ユーザー数を減らす。
  expected: システム利用状況のユーザー数の表示が減ること。
- case_no: 7-3
  sheet: B
  feature: システム利用状況
  category: '-'
  description: テーブル数を増やす。
  expected: システム利用状況のテーブル数の表示が増えること。
- case_no: 7-4
  sheet: B
  feature: システム利用状況
  category: '-'
  description: テーブル数を減らす。
  expected: システム利用状況のテーブル数の表示が減ること。
- case_no: 7-5
  sheet: B
  feature: システム利用状況
  category: '-'
  description: メール通知を実施する。
  expected: システム利用状況のメール通知数の表示が増えること。
- case_no: 89-1
  sheet: B
  feature: その他設定
  category: パスワードの定期変更を促す機能
  description: '①その他設定より、「パスワード強制変更画面表示の間隔日数」を1と設定して保存する。

    　

    　※その他設定の他設定箇所は以下の通り設定する。

    　　・「二段階認証を有効にする」　有効

    　　・「新規ユーザーのログイン時のパスワードリセットをOFFにする」　有効

    　　・初回ログイン時に利用規約を表示する　有効

    　　・通知の送信メールアドレスをSMTPで指定　無効

    　　・ロック自動解除時間(分)　5分'
  expected: '設定通りの処理となること。

    また、他の「その他設定」の設定項目へ無影響であることを確認する。'
- case_no: 8-1
  sheet: B
  feature: その他設定
  category: 二段階認証
  description: 二段階認証を有効化する。
  expected: 2段階認証の設定が行われること。
- case_no: 8-2
  sheet: B
  feature: その他設定
  category: 二段階認証
  description: 二段階認証を無効化する。
  expected: 2段階認証の設定が解除されること。
- case_no: 9-10
  sheet: B
  feature: 共通設定
  category: レコード
  description: レコードの詳細情報表示を行う。
  expected: エラーなくレコードの詳細情報表示が行えること。
- case_no: 9-11
  sheet: B
  feature: 共通設定
  category: レコード
  description: レコード編集を行う。
  expected: エラーなくレコードの編集が行えること。
- case_no: 9-12
  sheet: B
  feature: 共通設定
  category: レコード
  description: レコード削除を行う。
  expected: エラーなくレコードの削除が行えること。
- case_no: 9-1
  sheet: B
  feature: 共通設定
  category: レコード
  description: 追加を選択しレコードの追加を行う。
  expected: エラーなくレコード追加が可能なこと。
- case_no: 9-2
  sheet: B
  feature: 共通設定
  category: レコード
  description: CSVダウンロードを選択する。
  expected: エラーなく該当テーブルのレコード情報がCSV形式のファイルでダウンロードされること。
- case_no: 9-3
  sheet: B
  feature: 共通設定
  category: レコード
  description: CSVアップロードを選択する。
  expected: エラーなくCSV形式のファイルでレコード情報へアップロードできること。
- case_no: 9-4
  sheet: B
  feature: 共通設定
  category: レコード
  description: 全てのデータ削除を選択する。
  expected: エラーなく該当テーブルのレコード情報が全て削除されること。
- case_no: 9-5
  sheet: B
  feature: 共通設定
  category: レコード
  description: 集計を選択しデータ集計を行う。
  expected: エラーなく設定した情報が集計し表示されること。
- case_no: 9-6
  sheet: B
  feature: 共通設定
  category: レコード
  description: チャート追加を行う。
  expected: エラーなく設定した内容でチャート追加が行われること。
- case_no: 9-7
  sheet: B
  feature: 共通設定
  category: レコード
  description: 帳票登録を行う。
  expected: 'エラーなく帳票登録が行えること。

    帳票登録後、レコード詳細を表示すると「帳票出力」ボタンが表示されること。'
- case_no: 9-8
  sheet: B
  feature: 共通設定
  category: レコード
  description: データ検索を行う。
  expected: エラーなく検索結果に基づいた内容でレコード検索が行えること。
- case_no: 9-9
  sheet: B
  feature: 共通設定
  category: レコード
  description: データ編集を行う。
  expected: エラーなくレコード編集が行えること。
