group: ワークフロー
spec_file: tests/workflow.spec.js
base_url: '{{ TEST_BASE_URL }}'
cases:
- case_no: 106-01
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン1'
  description: '①以下のようにワークフロー申請を行う。

    ・Aさん(ユーザー)→組織(1人の承認が必要)

    ②組織(1名)で引き上げ承認できるか確認。'
  expected: '組織(1人)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-02
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン2'
  description: '①以下のようにワークフロー申請を行う。

    ・Aさん(ユーザー)→組織(全員の承認が必要)

    ②組織(全員)で引き上げ承認できるか確認。'
  expected: '組織(全員)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-03
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン3'
  description: '①以下のようにワークフロー申請を行う。

    ・Aさん(ユーザー)→Bさん(ユーザー)

    ②Bさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Bさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-04
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン4'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(1人の承認が必要)→Aさん(ユーザー)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Aさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-05
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン5'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(1人の承認が必要)→組織(1人の承認が必要)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: '組織(1人)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-06
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン6'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(1人の承認が必要)→組織(全員の承認が必要)

    ②組織(全員)で引き上げ承認できるか確認。'
  expected: '組織(全員)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-07
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン7'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(全員の承認が必要)→Aさん(ユーザー)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Aさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-08
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン8'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(全員の承認が必要)→組織(1人の承認が必要)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: '組織(1人)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-09
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン9'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(全員の承認が必要)→組織(全員の承認が必要)

    ②組織(全員)で引き上げ承認できるか確認。'
  expected: '組織(全員)で引き上げ承認ができないこと。

    ※「引き上げ承認」ボタンが表示されないこと。'
- case_no: 106-10
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン10'
  description: '①以下のようにワークフロー申請を行う。

    ・Aさん(ユーザー)→Bさん(ユーザー)→Cさん(ユーザー)

    ②Bさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Bさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-11
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン11'
  description: '①以下のようにワークフロー申請を行う。

    ・Aさん(ユーザー)→Bさん(ユーザー)→Cさん(ユーザー)

    ②Cさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Cさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-12
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン12'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(1人の承認が必要)→Aさん(ユーザー)→Bさん(ユーザー)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Aさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-13
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン13'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(1人の承認が必要)→Aさん(ユーザー)→Bさん(ユーザー)

    ②Bさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Bさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-14
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン14'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(全員の承認が必要)→Aさん(ユーザー)→Bさん(ユーザー)

    ②Aさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Aさん(ユーザー)で引き上げ承認ができること。
- case_no: 106-15
  sheet: B
  feature: ワークフロー
  category: '引き上げ承認

    パータン15'
  description: '①以下のようにワークフロー申請を行う。

    ・組織(全員の承認が必要)→Aさん(ユーザー)→Bさん(ユーザー)

    ②Bさん(ユーザー)で引き上げ承認できるか確認。'
  expected: Bさん(ユーザー)で引き上げ承認ができること。
- case_no: 111-01
  sheet: B
  feature: ワークフロー
  category: ''
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を1つチェックし「一括承認」をクリック'
  expected: '一括承認

    ・1つ選択'
- case_no: 111-02
  sheet: B
  feature: ワークフロー
  category: '一括承認

    ・複数選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括承認」をクリック'
  expected: エラーなく処理が完了すること。
- case_no: 111-03
  sheet: B
  feature: ワークフロー
  category: '一括承認

    ・承認時コメント入力'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括承認」をクリック

    ③承認時コメント入力を行う'
  expected: エラーなく処理が完了すること。
- case_no: 111-04
  sheet: B
  feature: ワークフロー
  category: '一括承認

    ・承認時コメント入力しない'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括承認」をクリック

    ③承認時コメント入力を行わない'
  expected: エラーなく処理が完了すること。
- case_no: 111-05
  sheet: B
  feature: ワークフロー
  category: '一括削除

    ・1つ選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を1つチェックし「一括削除」をクリック

    ※下書きや申請取り下げ後のレコードに対して実施'
  expected: エラーなく処理が完了すること。
- case_no: 111-06
  sheet: B
  feature: ワークフロー
  category: '一括削除

    ・複数選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括削除」をクリック

    ※下書きや申請取り下げ後のレコードに対して実施'
  expected: エラーなく処理が完了すること。
- case_no: 111-07
  sheet: B
  feature: ワークフロー
  category: '一括削除

    ・承認時コメント入力'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括削除」をクリック

    ③承認時コメント入力を行う'
  expected: エラーなく処理が完了すること。
- case_no: 111-08
  sheet: B
  feature: ワークフロー
  category: '一括削除

    ・承認時コメント入力しない'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括削除」をクリック

    ③承認時コメント入力を行わない'
  expected: エラーなく処理が完了すること。
- case_no: 111-09
  sheet: B
  feature: ワークフロー
  category: '一括否認

    ・1つ選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を1つチェックし「一括否認」をクリック'
  expected: エラーなく処理が完了すること。
- case_no: 111-10
  sheet: B
  feature: ワークフロー
  category: '一括否認

    ・複数選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括否認」をクリック'
  expected: エラーなく処理が完了すること。
- case_no: 111-11
  sheet: B
  feature: ワークフロー
  category: '一括否認

    ・承認時コメント入力'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括否認」をクリック

    ③承認時コメント入力を行う'
  expected: エラーなく処理が完了すること。
- case_no: 111-12
  sheet: B
  feature: ワークフロー
  category: '一括否認

    ・承認時コメント入力しない'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括否認」をクリック

    ③承認時コメント入力を行わない'
  expected: エラーなく処理が完了すること。
- case_no: 111-13
  sheet: B
  feature: ワークフロー
  category: '一括取り下げ

    ・1つ選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を1つチェックし「一括取り下げ」をクリック'
  expected: エラーなく処理が完了すること。
- case_no: 111-14
  sheet: B
  feature: ワークフロー
  category: '一括取り下げ

    ・複数選択'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括取り下げ」をクリック'
  expected: エラーなく処理が完了すること。
- case_no: 111-15
  sheet: B
  feature: ワークフロー
  category: '一括取り下げ

    ・承認時コメント入力'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括取り下げ」をクリック

    ③承認時コメント入力を行う'
  expected: エラーなく処理が完了すること。
- case_no: 111-16
  sheet: B
  feature: ワークフロー
  category: '一括取り下げ

    ・承認時コメント入力しない'
  description: '①ワークフロー申請を実施

    ②該当のテーブル一覧より、①の申請を複数チェックし「一括取り下げ」をクリック

    ③承認時コメント入力を行わない'
  expected: エラーなく処理が完了すること。
- case_no: 11-1
  sheet: B
  feature: ワークフロー
  category: ''
  description: 該当テーブルに対してワークフロー設定を行う。
  expected: エラーなく承認機能の実装が行えること。
- case_no: 11-2
  sheet: B
  feature: ワークフロー
  category: ''
  description: ユーザーAがBに対して申請し、承認・否認されるかどうか
  expected: ''
- case_no: 11-3
  sheet: B
  feature: ワークフロー
  category: ''
  description: ユーザーAがB、 C両方に申請し、両方OKで承認されるかどうか、NGの時に否認されるかどうか。また、Aの申請時はBに、Bが承認したときにはCに、C承認時はAにメール通知と、画面上での通知が正しくいっているか
  expected: ''
- case_no: 11-4
  sheet: B
  feature: ワークフロー
  category: ''
  description: 否認された後のフロー
  expected: 編集から再申請出来できればOK
- case_no: 11-5
  sheet: B
  feature: ワークフロー
  category: ''
  description: 申請相手の組織の誰かがOK・全員がOK で承認になる場合
  expected: 承認されていることが確認でればOK
- case_no: 11-6
  sheet: B
  feature: ワークフロー
  category: ''
  description: ワークフロー承認者はデータ編集可能　にチェックするしないで反映されるか
  expected: ''
- case_no: 11-7
  sheet: B
  feature: ワークフロー
  category: ''
  description: 再申請のチェックボックス　承認者申請画面の再編集できるか
  expected: ''
- case_no: 11-8
  sheet: B
  feature: ワークフロー
  category: ''
  description: ワークフローのフローを限定する　承認者の固定、条件指定（組織ごとに）
  expected: ''
- case_no: 11-9
  sheet: B
  feature: ワークフロー
  category: ''
  description: 否認→否認された申請を再編集→再申請→承認のフロー
  expected: ''
- case_no: '166'
  sheet: B
  feature: ワークフロー
  category: 自分自身を承認者に入れていた場合
  description: 自分自身を承認者に入れていた場合や、自分自身が引き上げ承認した場合、自分自身が承認組織・役職に含まれている場合、問題ないか確認する。
  expected: 全ての動作に問題やエラー発生がない事を確認する。
- case_no: 21-1
  sheet: B
  feature: ワークフロー
  category: 設定
  description: "① テーブルの管理より、対象テーブルの「追加オプション設定」を開き\n　 ワークフロー　有効　へチェック後 以下を有効にする\n\n\
    \   ・ワークフロー承認者はデータ編集可能\n\n② ①で設定したテーブルで追加登録を行いワークフロー申請を行う。"
  expected: ワークフロー承認者にて、申請データの編集が可能であることを確認する。
- case_no: 21-2
  sheet: B
  feature: ワークフロー
  category: 設定
  description: "① テーブルの管理より、対象テーブルの「追加オプション設定」を開き\n　 ワークフロー　有効　へチェック後 以下を有効にする\n\n\
    \    ・一度承認されたデータも再申請可能\n\n② ①で設定したテーブルで追加登録を行いワークフロー申請を行い最終承認まで完了する"
  expected: 承認完了後に、データ変更し再申請が可能であることを確認する。
- case_no: 21-3
  sheet: B
  feature: ワークフロー
  category: 設定
  description: "① テーブルの管理より、対象テーブルの「追加オプション設定」を開き\n　 ワークフロー　有効　へチェック後 以下を有効にする\n\n\
    \ 　・ワークフローのフローを固定する\n\n② 「テンプレートの追加」ボタンを押下し、以下設定を行う。\n　　\n　　＜条件の追加＞\n　   ・ログインユーザー　が次と一致　userA\n\
    　　＜申請フローの追加＞\n　　・ユーザーにチェック\n　　・ユーザー：マスターAを選択"
  expected: 設定通り、ワークフローのフローの固定ができていることを確認する。
- case_no: 21-4
  sheet: B
  feature: ワークフロー
  category: 取り下げ
  description: '① ワークフロー設定済みのテーブル開き、レコードの追加を実施

    ② ①の際、承認者の設定およびコメントの入力を行う

    ③ 申請中のレコードを開き、申請の取り下げ処理を行う'
  expected: ワークフロー申請の取り下げがエラーなく完了すること。
- case_no: 28-1
  sheet: B
  feature: ワークフロー
  category: '承認者削除(ユーザー)

    ※ワークフロー承認済み'
  description: '①ワークフローの承認者に「ユーザー」をセットし申請する。

    ②承認者に設定された「ユーザー」で承認を行い、ワークフローを完了する。

    ③①で承認者にセットされている「ユーザー」の削除を行う。'
  expected: '他機能に影響なく且つエラー等発生しないこと。


    削除した承認ユーザー名が表示されたままとなっていること'
- case_no: 28-2
  sheet: B
  feature: ワークフロー
  category: '承認者削除(組織)

    ※ワークフロー承認済み'
  description: '①ワークフローの承認者に「組織」をセットし申請する。

    ②承認者に設定された「組織」で承認を行い、ワークフローを完了する。

    ③①で承認者にセットされている「組織」の削除を行う。'
  expected: '他機能に影響なく且つエラー等発生しないこと。


    削除した承認組織が「!削除された組織!(XX)」と表示されていること。'
- case_no: 28-3
  sheet: B
  feature: ワークフロー
  category: '承認者削除(ユーザー)

    ※ワークフロー申請中'
  description: '①ワークフローの承認者に「ユーザー」をセットし申請する。

    ②①で承認者にセットされた「ユーザー」の削除を行う。'
  expected: '他機能に影響なく且つエラー等発生しないこと。


    削除した承認ユーザー名が表示されたままとなっていること'
- case_no: 28-4
  sheet: B
  feature: ワークフロー
  category: '承認者削除(組織)

    ※ワークフロー申請中'
  description: '①ワークフローの承認者に「組織」をセットし申請する。

    ②①で承認者にセットされた「組織」の削除を行う。'
  expected: '他機能に影響なく且つエラー等発生しないこと。


    削除した承認組織が「!削除された組織!(XX)」と表示されていること。'
- case_no: '296'
  sheet: B
  feature: ワークフロー
  category: 一つ戻す機能
  description: https://loftal.pigeon-cloud.com/admin/dataset__90/view/245
  expected: 想定通りの結果となること。
- case_no: 36-1
  sheet: B
  feature: ワークフロー
  category: 通知(ユーザー)
  description: ①「ユーザー」を申請者としてワークフロー申請を行う。
  expected: 申請者としてセットした「ユーザー」に対して通知が届くこと。
- case_no: 36-2
  sheet: B
  feature: ワークフロー
  category: 通知(組織)
  description: ①「組織」を申請者としてワークフロー申請を行う。
  expected: 申請者としてセットした「組織」に紐づいたユーザーに対して通知が届くこと。
- case_no: 395-1
  sheet: B
  feature: ワークフロー
  category: ''
  description: 申請時の件名と本文を変更を有効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-2
  sheet: B
  feature: ワークフロー
  category: ''
  description: 申請時の件名と本文を変更を無効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-3
  sheet: B
  feature: ワークフロー
  category: ''
  description: 否認時の件名と本文を変更を有効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-4
  sheet: B
  feature: ワークフロー
  category: ''
  description: 否認時の件名と本文を変更を無効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-5
  sheet: B
  feature: ワークフロー
  category: ''
  description: 完了時の件名と本文を変更を有効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-6
  sheet: B
  feature: ワークフロー
  category: ''
  description: 完了時の件名と本文を変更を無効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-7
  sheet: B
  feature: ワークフロー
  category: ''
  description: 取り下げ時の件名と本文を変更を有効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 395-8
  sheet: B
  feature: ワークフロー
  category: ''
  description: 取り下げ時の件名と本文を変更を無効にして通知を確認する
  expected: '想定通りの結果となること。

    https://henmi006.pigeon-demo.com/admin/dataset__84/'
- case_no: 64-1
  sheet: B
  feature: ワークフロー
  category: 申請取り下げ
  description: '①ワークフロー設定されたテーブルに対して、ワークフロー申請を行う。

    ②コメント欄へコメントを入力し、申請取り下げ処理を行う。'
  expected: ワークフロー設定を行ったユーザーに対して通知が行われコメントの内容も確認できること。
- case_no: 68-1
  sheet: B
  feature: ワークフロー
  category: 役職指定
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②ワークフロー申請の際、「組織(役職)」／「一人の承認が必要」を選択し、「組織」＋「役職」を選択し申請する。

    ③②で指定した「組織」＋「役職」のユーザーでログインを行い申請情報を確認後、コメント入力し「承認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    承認時のコメントが確認できること。'
- case_no: 68-2
  sheet: B
  feature: ワークフロー
  category: 役職指定
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②ワークフロー申請の際、「組織(役職)」／「一人の承認が必要」を選択し、「組織」＋「役職」を選択し申請する。

    ③②で指定した「組織」＋「役職」のユーザーでログインを行い申請情報を確認後、コメント入力し「否認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    否認時のコメントが確認できること。'
- case_no: 68-3
  sheet: B
  feature: ワークフロー
  category: 役職指定
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②ワークフロー申請の際、「組織(役職)」／「全員の承認が必要」を選択し、「組織」＋「役職」を選択し申請する。

    ③②で指定した「組織」＋「役職」の全ユーザーでログインを行い申請情報を確認後、コメント入力し「承認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    承認時のコメントが確認できること。'
- case_no: 68-4
  sheet: B
  feature: ワークフロー
  category: 役職指定
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②ワークフロー申請の際、「組織(役職)」／「全員の承認が必要」を選択し、「組織」＋「役職」を選択し申請する。

    ③②で指定した「組織」＋「役職」の全ユーザーでログインを行い申請情報を確認後、コメント入力し1名が「否認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    それぞれ入力したコメントが確認できること。'
- case_no: 68-5
  sheet: B
  feature: ワークフロー
  category: ワークフロー固定：「組織(役職)」／「一人の承認が必要」)
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②申請コメントを入力し、「申請」ボタンをクリックする。

    ③②で指定した「組織」＋「役職」のユーザーでログインを行い申請情報を確認後、コメント入力し「承認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    それぞれ入力したコメントが確認できること。'
- case_no: 68-6
  sheet: B
  feature: ワークフロー
  category: ワークフロー固定：「組織(役職)」／「一人の承認が必要」)
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②申請コメントを入力し、「申請」ボタンをクリックする。

    ③②で指定した「組織」＋「役職」のユーザーでログインを行い申請情報を確認後、コメント入力し「否認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    それぞれ入力したコメントが確認できること。'
- case_no: 68-7
  sheet: B
  feature: ワークフロー
  category: ワークフロー固定：「組織(役職)」／「全員の承認が必要」)
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②申請コメントを入力し、「申請」ボタンをクリックする。

    ③②で指定した「組織」＋「役職」の全ユーザーでログインを行い申請情報を確認後、コメント入力し「承認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    それぞれ入力したコメントが確認できること。'
- case_no: 68-8
  sheet: B
  feature: ワークフロー
  category: ワークフロー固定：「組織(役職)」／「全員の承認が必要」)
  description: '①ワークフロー対象のテーブル一覧を開き、データ追加を行う。

    ②申請コメントを入力し、「申請」ボタンをクリックする。

    ③②で指定した「組織」＋「役職」の全ユーザーでログインを行い申請情報を確認後、1名がコメント入力し「否認」をクリックする。'
  expected: 'エラーなくワークフロー処理が行われること。

    それぞれ入力したコメントが確認できること。'
